# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:57:51+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Source(Enum):
    email = 'email'
    web = 'web'
    file = 'file'
    chat = 'chat'


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class DocumentChunkMetadata(BaseModel):
    author: Optional[str] = Field(None, title='Author')
    collection_id: Optional[str] = Field(None, title='Collection Id')
    created_at: Optional[str] = Field(None, title='Created At')
    document_id: Optional[str] = Field(None, title='Document Id')
    keywords: Optional[List[str]] = Field(None, title='Keywords')
    language: Optional[str] = Field(None, title='Language')
    source: Optional[Source] = None
    source_id: Optional[str] = Field(None, title='Source Id')
    time_period: Optional[str] = Field(None, title='Time Period')
    updated_at: Optional[str] = Field(None, title='Updated At')
    url: Optional[str] = Field(None, title='Url')
    user_id: Optional[str] = Field(None, title='User Id')


class DocumentChunkWithScore(BaseModel):
    embedding: Optional[List[float]] = Field(None, title='Embedding')
    id: Optional[str] = Field(None, title='Id')
    metadata: DocumentChunkMetadata
    score: float = Field(..., title='Score')
    text: str = Field(..., title='Text')


class DocumentMetadataFilter(BaseModel):
    author: Optional[str] = Field(None, title='Author')
    collection_id: Optional[str] = Field(None, title='Collection Id')
    document_id: Optional[str] = Field(None, title='Document Id')
    end_date: Optional[str] = Field(None, title='End Date')
    keywords: Optional[List[str]] = Field(None, title='Keywords')
    language: Optional[str] = Field(None, title='Language')
    source: Optional[Source] = None
    source_id: Optional[str] = Field(None, title='Source Id')
    start_date: Optional[str] = Field(None, title='Start Date')
    time_period: Optional[str] = Field(None, title='Time Period')
    user_id: Optional[str] = Field(None, title='User Id')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')


class Query(BaseModel):
    filter: Optional[DocumentMetadataFilter] = None
    query: str = Field(..., title='Query')
    top_k: Optional[int] = Field(3, title='Top K')


class QueryRequest(BaseModel):
    namespace: Optional[str] = Field(None, title='Namespace')
    queries: List[Query] = Field(..., title='Queries')


class QueryResult(BaseModel):
    query: str = Field(..., title='Query')
    results: List[DocumentChunkWithScore] = Field(..., title='Results')


class QueryResponse(BaseModel):
    results: List[QueryResult] = Field(..., title='Results')
